# This workflow will build a Jekyll site and deploy it to GitHub Pages
# For more information on GitHub Actions, see: https://docs.github.com/en/actions/automating-your-workflow-with-github-actions/
# For more information on Jekyll and GitHub Pages, see: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll

name: Deploy Jekyll site to Pages

on:
  # Runs on pushes targeting the default branch (usually 'main')
  push:
    branches: ["main"]

  # Runs on pull requests targeting the default branch (for testing builds)
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the start and latest queued.
# However, do NOT cancel in-progress runs as we want to be able to roll back.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Not needed if you are not doing anything with git history

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.x' # Or your specific Ruby version if known
          bundler-cache: true # speeds up subsequent runs

      - name: Install Jekyll dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build --destination ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Path to the directory where your Jekyll site is built.
          # For Jekyll, this is typically the _site directory.
          path: './_site'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # This job depends on the build job completing successfully
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
